repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
        exclude_types: [xml, json]
    -   id: flake8
        args:
        - --max-line-length=160
        - --ignore=F403,F405,W504
    -   id: check-merge-conflict
-   repo: https://github.com/FalconSocial/pre-commit-python-sorter
    rev: 1.0.4
    hooks:
    -   id: python-import-sorter
        args:
        - --diff
